### ISSUE TITLE
Pause when reading from the socket

### ISSUE THREAD

**Issue by olgio** [RHazDev/RHazSockets#1]
Hello! When reading from a socket in the SocketMessenger class, you put the thread to sleep. This is not necessary because the readLine in the BufferedReader blocks the thread until it receives a new line.
This can cause latency problems

https://stackoverflow.com/questions/18746167/is-thread-sleep-necessary-when-reading-from-a-socket-stream/18746253

**Comment by Hazae41** [comment]
The new line would be read instantly after the last one, causing lags

**Comment by olgio** [comment]
I used the old version of Socket4mc without pauses and there were no problems with delays. Can you please add to the config parameter to disable the delay and change the buffer size (20 by default in your code)?
